[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "9d6628283b8e388e4b58a3fd2cab63ca9b572ab5"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "fa7c2e795173a5502578b37d1f5a452cb43cfc533b9b413aeea6a3c76f84398a"
    url = "https://github.com/maleadt/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.10.1+1/SuiteSparse_GPU.v5.10.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "f6a1b18152de96c2913f97b823b90fbd689ce63a"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "070f132b6500c74d148a9cd8f6f324752278c6da1573ef81c3719ea94fc9b293"
    url = "https://github.com/maleadt/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.10.1+1/SuiteSparse_GPU.v5.10.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
